##-- Riscv toolchain path
RISCV = ../../tools/xpack-risc_v/bin/riscv-none-elf
prog: code.bin

code.elf: sections.lds start.s main.c printf.c Makefile
	$(RISCV)-gcc -march=rv32e -mabi=ilp32e \
	-Wl,-Bstatic,-T,sections.lds,--strip-debug,-Map=code.map \
	-ffreestanding -nostdlib \
	-Os -o $@ start.s main.c -lgcc
	$(RISCV)-objdump -d $@ >code.lst
	$(RISCV)-size $@

code.bin: code.elf
	$(RISCV)-objcopy -O binary $< $@
	
dis: code.elf
	$(RISCV)-objdump -d $< >code.lst

# ---- Clean ----

clean:
	rm -f *.elf *.bin *~ *.lst *.map

.PHONY: prog
