#----------------------------------------
#-- Establecer nombre del componente
#----------------------------------------
DEPSIM = system.v laRVa.v uart.v spi.v
DEPSINT= pll.v system.v laRVa.v uart.v spi.v

HOME    =../tools
GTKWAVE =$(HOME)/tool-gtkwave/bin/gtkwave
IVERILOG=$(HOME)/toolchain-iverilog/bin/iverilog
VVP     =$(HOME)/toolchain-iverilog/bin/vvp
YOSIS   =$(HOME)/toolchain-yosys/bin/yosys
NEXTPNR =$(HOME)/toolchain-ice40/bin/nextpnr-ice40
ICEPACK =$(HOME)/toolchain-ice40/bin/icepack
ICEPROG =$(HOME)/toolchain-ice40/bin/iceprog
ICEBRAM =$(HOME)/toolchain-ice40/bin/icebram
ICELOAD =$(HOME)/lpc11loader/iceload
#-------------------------------------------------------
#-- Objetivo por defecto: hacer simulacion y sintesis
#-------------------------------------------------------
all: sim

#-------------------------------------------------------
#-- Fuentes de la ROM
#-------------------------------------------------------	
Firmware/code.bin:	Firmware/main.c Firmware/start.s
	make -C Firmware

rom.hex:	Firmware/code.bin tovhex.exe
	./tovhex.exe $< $@
#----------------------------------------------
#-- make sim
#----------------------------------------------
#-- Objetivo para hacer la simulacion del
#-- banco de pruebas
#----------------------------------------------

sim:	tb.v $(DEPSIM) rom.hex
	#-- Compilar
	$(IVERILOG) -DSIMULATION -DSIM -o tb.out tb.v 
	
	#-- Simular
	$(VVP) tb.out
	$(GTKWAVE) tb.vcd tb.gtkw &
	
#-----------------------------------------------
#-  make sint
#-----------------------------------------------
#-  Objetivo para realizar la sintetis completa
#- y dejar el diseno listo para su grabacion en
#- la FPGA
#-----------------------------------------------

#sint: main.bin
#	$(ICELOAD) -f 16 -c $<

burn: main.bin
	$(ICELOAD) $<

#term:
#	$(ICELOAD) -f 16 -t
	
#------------------------------
#-- Sintesis completa
#------------------------------
rand.hex:
	echo $(ICEBRAM)
	$(ICEBRAM) -g 32 2048 > rand.hex
#main.bin:	main.asc rom.hex
#	$(ICEPACK) main.asc main.bin
main.bin: main.asc rom.hex rand.hex Makefile
	$(ICEBRAM) rand.hex rom.hex < main.asc > final.asc
	$(ICEPACK) final.asc main.bin
main.asc: pines.pcf main.v $(DEPSINT) rand.hex
	#-- Sintesis 
	$(YOSIS) -p "synth_ice40 -relut" -o main.json main.v >sint.log
	#-- Place & route	
	$(NEXTPNR) --hx8k --pcf pines.pcf --json main.json --asc main.asc --package tq144:4k 2>pnr.log

#-- Limpiar todo
clean:
	rm -f *.asc *.blif *.out *.vcd *.json *.log *.lst *~
	
#-- tovhex
tovhex.exe:	tovhex.c
	gcc -O2 -w -o $@ $<
	
PHONY: all clean

	
